name: swb2_tests
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - pandas
  - matplotlib
  - xarray
  - scipy
  - netcdf4
  - h5netcdf
  - pyproj
  - proj-data
  - jupyterlab
  - ipykernel>=6.29
  - pyfao56
